"""add_google_calendar_event_id_to_bookings

Revision ID: 7020c2936c2b
Revises: 3ada4cb533ab
Create Date: 2026-06-21 05:14:27.733572
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7020c2936c2b'
down_revision: str | None = '3ada4cb533ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'google_calendar_event_id')
    # ### end Alembic commands ###

